const projects = [
    {
        companyName:"Bridge & roof Co. (India) Ltd",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2019",
        status: "Completed",
        location: "Dahej Gujarat",

    },
    {
        companyName:"Gujarat Alkalies and Chemicals Limited",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "PPA Project (Phase 1)",
        year: "2019",
        status: "Completed",
        location: "Dahej Gujarat",
    },
    {
        companyName:"Gujarat Alkalies and Chemicals Limited",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "PPA Project (Phase 2)",
        year: "2020",
        status: "Completed",
        location: "Dahej Gujarat",
    },
    {
        companyName:"KLJ Petroplast",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2022",
        status: "Completed",
        location: "Jhagadia Gujarat",
    },
    {
        companyName:"Atvantic Finechem Pvt. Ltd.",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2023",
        status: "Completed",
        location: "Dahej Gujarat",
    },
    {
        companyName:"Vijay M. Mistry Construction Pvt. Ltd.",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2025",
        status: "Completed",
        location: "Mundra Gujarat",
    },
    {
        companyName:"Adani Cement Indus LTD.",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2024",
        status: "Completed",
        location: "Dahej Gujarat",
    },
    {
        companyName:"Ambuja Cement / Adani Cement LTD.",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2025",
        status: "Completed",
        location: "Hazira Gujarat",
    },
    {
        companyName:"Deepak Fertilizer & Petrochemicals ",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling & Pile testing services",
        year: "2025",
        status: "Completed",
        location: "Dahej Gujarat",
    },
    {
        companyName:"RAYZON SOLAR PVT. LTD.",
        companyLogo:"",
        category: "Renewable Energy",
        projectDetails: "Piling work",
        year: "2025",
        status: "Completed",
        location: "Kosamba Gujarat",
    },
    {
        companyName:"ECR Buildtech PVT. LTD.",
        companyLogo:"",
        category: "Renewable Energy",
        projectDetails: "Piling work",
        year: "2025",
        status: "In Progress",
        location: "Kosamba Gujarat",
    },
    {
        companyName:"Gujarat JHM Hotels PVT. LTD.",
        companyLogo:"",
        category: "Government Projects",
        projectDetails: "Piling & Pile testing services",
        year: "2024",
        status: "Completed",
        location: "Surat Gujarat",
    },
    {
        companyName:"AM/NS India LTD.",
        companyLogo:"",
        category: "Industrial Construction",
        projectDetails: "Piling work",
        year: "2025",
        status: "In Progress",
        location: "Hazira Gujarat",
    },
];

export { projects };